<Project>

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <LibraryPath>$(MSBuildThisFileDirectory)lib\</LibraryPath>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts\</ArtifactsPath>
  </PropertyGroup>

</Project>
