<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AbsoluteFriends.Pilgrimage</AssemblyName>
    <RootNamespace>AbsoluteFriends.Pilgrimage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AbsoluteFriends.csproj" Private="false" />
    <ProjectReference Include="..\core\AbsoluteCore.csproj" Private="false" />
  </ItemGroup>

</Project>
