<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RippleFriends.Players</AssemblyName>
    <RootNamespace>RippleFriends.Players</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RippleFriends.csproj" Private="false" />
    <ProjectReference Include="..\core\RippleCore.csproj" Private="false" />
  </ItemGroup>

</Project>
